# Generated by Django 3.1.6 on 2021-02-14 23:05

from django.db import migrations, models
import django.db.models.deletion
import post.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='제목')),
                ('contents', models.TextField(verbose_name='내용')),
                ('disclosure', models.SmallIntegerField(choices=[(0, 'private'), (1, 'public')])),
                ('hits', models.IntegerField(default=0, verbose_name='조회수')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='글쓴이')),
            ],
            options={
                'verbose_name': '게시판',
                'verbose_name_plural': '게시판',
                'db_table': 'haeum board',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='제목')),
                ('image', models.ImageField(upload_to=post.models.image_upload_to)),
                ('order', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': '사진',
                'verbose_name_plural': '사진',
                'db_table': 'haeum photo',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Post_thanks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(verbose_name='내용')),
                ('image_url', models.CharField(max_length=30, verbose_name='이미지url')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.board', verbose_name='게시글')),
            ],
        ),
    ]
