# Generated by Django 3.1.5 on 2021-02-18 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 18, 22, 51, 43, 344279), verbose_name='날짜'),
        ),
    ]
