# Generated by Django 3.1.6 on 2021-04-22 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_photo_reg_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post_thanks',
            options={'verbose_name': '감사열매', 'verbose_name_plural': '감사열매'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 21, 8, 24, 146422), verbose_name='날짜'),
        ),
        migrations.AlterModelTable(
            name='post_thanks',
            table='haeum thanks',
        ),
    ]
