# Generated by Django 3.1.6 on 2021-04-22 12:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('post', '0003_auto_20210422_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 21, 10, 59, 561851), verbose_name='날짜'),
        ),
        migrations.CreateModel(
            name='Board_thanks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='제목')),
                ('contents', models.TextField(verbose_name='내용')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='글쓴이')),
            ],
            options={
                'verbose_name': '감사노트',
                'verbose_name_plural': '감사노트',
                'db_table': 'thanks board',
            },
        ),
    ]
