# Generated by Django 3.1.6 on 2021-02-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('password', models.CharField(max_length=128, verbose_name='비밀번호')),
            ],
            options={
                'verbose_name': '셀원',
                'verbose_name_plural': '셀원',
                'db_table': 'haeum user',
            },
        ),
    ]
